# ── Constantes generales ─────────────────────────────────────────────────────
TOTAL_RONDAS    = 10
COOLDOWN        = 3
MIN_EST         = 3
MAX_EST         = 5
REGEX_NOMBRE    = r"[A-Za-záéíóúÁÉÍÓÚñÑ ]+"
TIEMPO_PREGUNTA = 30
UMBRAL_COLAPSO  = 60   # puntaje promedio mínimo para no colapsar
UMBRAL_ROJO     = 30   # indicador crítico → colapso inmediato

# ── Mix de preguntas por dificultad de partida ────────────────────────────────
# porcentaje aprox. de cada nivel de pregunta en cada modo
MEZCLA_PREGUNTAS = {
    "Fácil":   {"facil": 0.60, "normal": 0.35, "dificil": 0.05},
    "Normal":  {"facil": 0.20, "normal": 0.55, "dificil": 0.25},
    "Difícil": {"facil": 0.05, "normal": 0.35, "dificil": 0.60},
}

# ── Penalizaciones por dificultad ─────────────────────────────────────────────
DIFICULTADES = {
    "Fácil":   {"penalizacion": 10, "mult_par": 2, "estrellas": 1,
                "eventos_peso": {"positivos": 0.55, "negativos": 0.45}},
    "Normal":  {"penalizacion": 15, "mult_par": 2, "estrellas": 2,
                "eventos_peso": {"positivos": 0.40, "negativos": 0.60}},
    "Difícil": {"penalizacion": 20, "mult_par": 2, "estrellas": 3,
                "eventos_peso": {"positivos": 0.25, "negativos": 0.75}},
}

# ── Colores e iconos de indicadores ──────────────────────────────────────────
IND_COLOR = {
    "economia":        ("#fbbf24", "💰"),
    "medio_ambiente":  ("#34d399", "🌿"),
    "energia":         ("#60a5fa", "⚡"),
    "bienestar_social":("#f472b6", "❤️"),
}
IND_LABEL = {
    "economia":        "Economía",
    "medio_ambiente":  "Medio Amb.",
    "energia":         "Energía",
    "bienestar_social":"Bienestar",
}
CAT_COLOR = {
    "Python":        "#6366f1",
    "PSeInt":        "#8b5cf6",
    "Cálculo":       "#06b6d4",
    "Derivadas":     "#10b981",
    "Física MRU":    "#f59e0b",
    "Física MRUA":   "#ef4444",
    "Matrices":      "#ec4899",
    "Lógica":        "#f97316",
    "Álgebra":       "#84cc16",
    "Estadística":   "#a78bfa",
}

# ── Decisiones ────────────────────────────────────────────────────────────────
DECISIONES = {
    "Construir fábrica":     {"emoji":"🏭","economia":18,"medio_ambiente":-15,"energia":-8,"bienestar_social":-3},
    "Crear parque natural":  {"emoji":"🌳","economia":-8,"medio_ambiente":18,"energia":-3,"bienestar_social":12},
    "Instalar paneles solares":{"emoji":"☀️","economia":-12,"medio_ambiente":12,"energia":22,"bienestar_social":-2},
    "Construir escuelas":    {"emoji":"🏫","economia":-12,"medio_ambiente":-2,"energia":-6,"bienestar_social":22},
    "Ampliar autopistas":    {"emoji":"🛣️","economia":12,"medio_ambiente":-18,"energia":-12,"bienestar_social":-5},
    "Agricultura urbana":    {"emoji":"🌱","economia":6,"medio_ambiente":12,"energia":4,"bienestar_social":10},
    "Mejorar hospitales":    {"emoji":"🏥","economia":-18,"medio_ambiente":-2,"energia":-6,"bienestar_social":28},
    "Planta de carbón":      {"emoji":"⚫","economia":22,"medio_ambiente":-25,"energia":28,"bienestar_social":-10},
}

# ── Eventos ───────────────────────────────────────────────────────────────────
EVENTOS_NEGATIVOS = [
    {"nombre":"Tormenta devastadora","indicador":"medio_ambiente","valor":-14},
    {"nombre":"Pandemia regional",   "indicador":"bienestar_social","valor":-16},
    {"nombre":"Apagón masivo",       "indicador":"energia","valor":-14},
    {"nombre":"Recesión económica",  "indicador":"economia","valor":-14},
    {"nombre":"Incendio forestal",   "indicador":"medio_ambiente","valor":-18},
    {"nombre":"Sequía prolongada",   "indicador":"medio_ambiente","valor":-12},
    {"nombre":"Crisis industrial",   "indicador":"economia","valor":-12},
    {"nombre":"Inundación urbana",   "indicador":"bienestar_social","valor":-13},
    {"nombre":"Fallo de infraestructura","indicador":"energia","valor":-16},
    {"nombre":"Brote de enfermedad", "indicador":"bienestar_social","valor":-12},
]
EVENTOS_POSITIVOS = [
    {"nombre":"Boom económico",      "indicador":"economia","valor":10},
    {"nombre":"Ahorro energético",   "indicador":"energia","valor":9},
    {"nombre":"Gran cosecha",        "indicador":"medio_ambiente","valor":8},
    {"nombre":"Festival cultural",   "indicador":"bienestar_social","valor":10},
    {"nombre":"Inversión extranjera","indicador":"economia","valor":12},
    {"nombre":"Beca educativa masiva","indicador":"bienestar_social","valor":9},
    {"nombre":"Energía renovable bonus","indicador":"energia","valor":8},
]
EVENTOS = EVENTOS_NEGATIVOS + EVENTOS_POSITIVOS

# ── Atributos comprables con estrellas ────────────────────────────────────────
# Se activan ANTES de elegir decisión en una ronda. Duran 1 ronda.
ATRIBUTOS = {
    "escudo_ciudad":    {"emoji":"🛡️","nombre":"Escudo de Ciudad",
                         "desc":"Reduce al 50% el impacto de eventos negativos esta ronda.",
                         "costo":30, "tipo":"ronda"},
    "prot_economia":    {"emoji":"💰","nombre":"Protección Económica",
                         "desc":"Ignora el siguiente efecto negativo en Economía.",
                         "costo":10, "tipo":"ronda"},
    "prot_ambiente":    {"emoji":"🌿","nombre":"Protección Ambiental",
                         "desc":"Ignora el siguiente efecto negativo en Medio Ambiente.",
                         "costo":15, "tipo":"ronda"},
    "prot_energia":     {"emoji":"⚡","nombre":"Protección Energética",
                         "desc":"Ignora el siguiente efecto negativo en Energía.",
                         "costo":15, "tipo":"ronda"},
    "prot_bienestar":   {"emoji":"❤️","nombre":"Protección Social",
                         "desc":"Ignora el siguiente efecto negativo en Bienestar.",
                         "costo":15, "tipo":"ronda"},
    "segunda_oportunidad":{"emoji":"🔄","nombre":"Segunda Oportunidad",
                           "desc":"Si fallas la pregunta, puedes responderla una vez más.",
                           "costo":20, "tipo":"pregunta"},
    "tiempo_extra":     {"emoji":"⏱️","nombre":"Tiempo Extra",
                         "desc":"+15 segundos en el temporizador de esta ronda.",
                         "costo":12, "tipo":"pregunta"},
    "doble_efecto":     {"emoji":"✨","nombre":"Doble Efecto",
                         "desc":"Si aciertas, los efectos positivos de la decisión se duplican.",
                         "costo":25, "tipo":"ronda"},
}

# ── Misiones ──────────────────────────────────────────────────────────────────
MISIONES = [
    {"id":"m01","nombre":"Primera Partida","desc":"Completa tu primera partida.",
     "recompensa":2,"dif":"todas","tipo":"partidas","meta":1},
    {"id":"m02","nombre":"Racha de 3","desc":"Responde 3 preguntas seguidas correctamente.",
     "recompensa":3,"dif":"todas","tipo":"racha","meta":3},
    {"id":"m03","nombre":"Racha de 5","desc":"Responde 5 preguntas seguidas correctamente.",
     "recompensa":5,"dif":"todas","tipo":"racha","meta":5},
    {"id":"m04","nombre":"Ciudad Verde","desc":"Termina con Medio Ambiente > 70.",
     "recompensa":4,"dif":"todas","tipo":"indicador","ind":"medio_ambiente","meta":70},
    {"id":"m05","nombre":"Economía Próspera","desc":"Termina con Economía > 75.",
     "recompensa":4,"dif":"todas","tipo":"indicador","ind":"economia","meta":75},
    {"id":"m06","nombre":"Sin Colapso","desc":"Completa 10 rondas sin que ningún indicador llegue a rojo.",
     "recompensa":6,"dif":"todas","tipo":"sin_rojo","meta":1},
    {"id":"m07","nombre":"Maestro Normal","desc":"Gana una partida en Normal.",
     "recompensa":5,"dif":"Normal","tipo":"victoria","meta":1},
    {"id":"m08","nombre":"Héroe Difícil","desc":"Gana una partida en Difícil.",
     "recompensa":8,"dif":"Difícil","tipo":"victoria","meta":1},
    {"id":"m09","nombre":"10/10 Correctas","desc":"Responde correctamente las 10 preguntas de una partida.",
     "recompensa":10,"dif":"todas","tipo":"correctas","meta":10},
    {"id":"m10","nombre":"Ciudad Equilibrada","desc":"Termina con todos los indicadores > 50.",
     "recompensa":7,"dif":"todas","tipo":"todos_sobre","meta":50},
    {"id":"m11","nombre":"Explorador","desc":"Usa todas las decisiones al menos una vez en una partida.",
     "recompensa":4,"dif":"todas","tipo":"decisiones_usadas","meta":8},
    {"id":"m12","nombre":"Resistente","desc":"Supera 3 eventos negativos seguidos sin colapsar.",
     "recompensa":5,"dif":"Normal","tipo":"eventos_neg","meta":3},
]

# ── 50 Logros ──────────────────────────────────────────────────────────────────
LOGROS = [
    # — Primeras veces —
    {"id":"l01","emoji":"🌱","nombre":"Primeros Pasos","desc":"Completa tu primera ronda.",
     "como":"Juega y completa la ronda 1 en cualquier dificultad.","tipo":"rondas","meta":1,"estrellas":1},
    {"id":"l02","emoji":"🏙️","nombre":"Alcalde Novato","desc":"Completa tu primera partida completa.",
     "como":"Juega las 10 rondas en cualquier dificultad.","tipo":"partidas","meta":1,"estrellas":2},
    {"id":"l03","emoji":"🎓","nombre":"Estudiante Aplicado","desc":"Responde tu primera pregunta correcta.",
     "como":"Acierta al menos 1 pregunta en una partida.","tipo":"correctas_total","meta":1,"estrellas":1},
    # — Preguntas —
    {"id":"l04","emoji":"🧠","nombre":"Mente Brillante","desc":"10 respuestas correctas en una partida.",
     "como":"Acierta las 10 preguntas de una partida completa.","tipo":"correctas_partida","meta":10,"estrellas":5},
    {"id":"l05","emoji":"⚡","nombre":"Relámpago","desc":"Responde en menos de 5 s.",
     "como":"Confirma tu respuesta antes de que pasen 5 segundos.","tipo":"velocidad","meta":5,"estrellas":3},
    {"id":"l06","emoji":"🔥","nombre":"En Llamas","desc":"Racha de 5 correctas seguidas.",
     "como":"Responde 5 preguntas seguidas sin fallar.","tipo":"racha","meta":5,"estrellas":4},
    {"id":"l07","emoji":"💯","nombre":"Perfeccionista","desc":"Racha de 10 correctas seguidas.",
     "como":"Responde 10 preguntas seguidas sin fallar.","tipo":"racha","meta":10,"estrellas":8},
    {"id":"l08","emoji":"📚","nombre":"Enciclopedia","desc":"50 respuestas correctas totales.",
     "como":"Acumula 50 aciertos a lo largo de tus partidas.","tipo":"correctas_total","meta":50,"estrellas":6},
    {"id":"l09","emoji":"🏆","nombre":"Maestro del Saber","desc":"100 respuestas correctas totales.",
     "como":"Acumula 100 aciertos en total.","tipo":"correctas_total","meta":100,"estrellas":10},
    {"id":"l10","emoji":"🕐","nombre":"Contrarreloj","desc":"Responde con menos de 3 s restantes.",
     "como":"Confirma la respuesta cuando queden 2 s o menos.","tipo":"casi_tiempo","meta":1,"estrellas":3},
    # — Dificultad —
    {"id":"l11","emoji":"🟢","nombre":"Ciudad Fácil","desc":"Gana en dificultad Fácil.",
     "como":"Completa 10 rondas sin colapso en Fácil.","tipo":"victoria","dif":"Fácil","meta":1,"estrellas":2},
    {"id":"l12","emoji":"🟡","nombre":"Ciudad Normal","desc":"Gana en dificultad Normal.",
     "como":"Completa 10 rondas sin colapso en Normal.","tipo":"victoria","dif":"Normal","meta":1,"estrellas":3},
    {"id":"l13","emoji":"🔴","nombre":"Ciudad Difícil","desc":"Gana en dificultad Difícil.",
     "como":"Completa 10 rondas sin colapso en Difícil.","tipo":"victoria","dif":"Difícil","meta":1,"estrellas":6},
    {"id":"l14","emoji":"👑","nombre":"Leyenda Urbana","desc":"Gana en las 3 dificultades.",
     "como":"Consigue victoria en Fácil, Normal y Difícil.","tipo":"victoria_3","meta":3,"estrellas":12},
    {"id":"l15","emoji":"💎","nombre":"Élite","desc":"Gana 5 veces en Difícil.",
     "como":"Acumula 5 victorias en dificultad Difícil.","tipo":"victoria_dif_count","dif":"Difícil","meta":5,"estrellas":15},
    # — Indicadores —
    {"id":"l16","emoji":"🌿","nombre":"Guardián Verde","desc":"Termina con Medio Ambiente > 80.",
     "como":"Cierra la última ronda con el indicador de Medio Ambiente por encima de 80.","tipo":"indicador_fin","ind":"medio_ambiente","meta":80,"estrellas":4},
    {"id":"l17","emoji":"💰","nombre":"Magnate","desc":"Termina con Economía > 80.",
     "como":"Cierra con Economía superior a 80.","tipo":"indicador_fin","ind":"economia","meta":80,"estrellas":4},
    {"id":"l18","emoji":"⚡","nombre":"Reactor","desc":"Termina con Energía > 80.",
     "como":"Cierra con Energía superior a 80.","tipo":"indicador_fin","ind":"energia","meta":80,"estrellas":4},
    {"id":"l19","emoji":"❤️","nombre":"Corazón de Ciudad","desc":"Termina con Bienestar > 80.",
     "como":"Cierra con Bienestar Social superior a 80.","tipo":"indicador_fin","ind":"bienestar_social","meta":80,"estrellas":4},
    {"id":"l20","emoji":"🌈","nombre":"Ciudad Perfecta","desc":"Todos los indicadores > 75 al final.",
     "como":"Los 4 indicadores deben superar 75 al terminar la partida.","tipo":"todos_sobre","meta":75,"estrellas":10},
    {"id":"l21","emoji":"🛡️","nombre":"Fortaleza","desc":"Ningún indicador baja de 40 en toda la partida.",
     "como":"Mantén todos los indicadores >= 40 durante las 10 rondas.","tipo":"min_global","meta":40,"estrellas":5},
    {"id":"l22","emoji":"🚨","nombre":"Al Límite","desc":"Recupera un indicador desde rojo (< 30) hasta verde (>60).",
     "como":"Un indicador en rojo debe subir a 60+ antes de terminar.","tipo":"recuperacion","meta":1,"estrellas":7},
    # — Decisiones —
    {"id":"l23","emoji":"🔬","nombre":"Científico","desc":"Usa Instalar paneles solares 3 veces en total.",
     "como":"Elige Instalar paneles solares en 3 partidas distintas.","tipo":"decision_count","dec":"Instalar paneles solares","meta":3,"estrellas":3},
    {"id":"l24","emoji":"📖","nombre":"Educador","desc":"Usa Construir escuelas 5 veces en total.",
     "como":"Elige Construir escuelas acumulando 5 usos.","tipo":"decision_count","dec":"Construir escuelas","meta":5,"estrellas":4},
    {"id":"l25","emoji":"🗺️","nombre":"Explorador Urbano","desc":"Usa todas las decisiones al menos una vez en 1 partida.",
     "como":"Durante 10 rondas, elige cada una de las 8 decisiones al menos 1 vez.","tipo":"decisiones_todas","meta":8,"estrellas":6},
    {"id":"l26","emoji":"♻️","nombre":"Ecologista","desc":"No uses Fábrica ni Planta de carbón en una partida.",
     "como":"Completa 10 rondas sin elegir Construir fábrica ni Planta de carbón.","tipo":"sin_decision","meta":1,"estrellas":5},
    # — Estrellas y atributos —
    {"id":"l27","emoji":"⭐","nombre":"Coleccionista","desc":"Acumula 20 estrellas.",
     "como":"Gana estrellas con partidas y misiones hasta llegar a 20.","tipo":"estrellas","meta":20,"estrellas":0},
    {"id":"l28","emoji":"🌟","nombre":"Supernova","desc":"Acumula 50 estrellas.",
     "como":"Llega a 50 estrellas totales.","tipo":"estrellas","meta":50,"estrellas":0},
    {"id":"l29","emoji":"🛡️","nombre":"Defensor","desc":"Usa el Escudo de Ciudad 3 veces.",
     "como":"Activa el atributo Escudo de Ciudad en 3 rondas distintas.","tipo":"atributo_count","atr":"escudo_ciudad","meta":3,"estrellas":3},
    {"id":"l30","emoji":"🔄","nombre":"Segunda Vida","desc":"Usa Segunda Oportunidad y acierta.",
     "como":"Activa Segunda Oportunidad y responde correctamente en el segundo intento.","tipo":"segunda_ok","meta":1,"estrellas":4},
    # — Misiones —
    {"id":"l31","emoji":"📋","nombre":"Misionero","desc":"Completa 3 misiones.",
     "como":"Canjea 3 misiones distintas.","tipo":"misiones_count","meta":3,"estrellas":4},
    {"id":"l32","emoji":"🏅","nombre":"Veterano de Misiones","desc":"Completa 8 misiones.",
     "como":"Canjea 8 misiones en total.","tipo":"misiones_count","meta":8,"estrellas":8},
    # — Raras / especiales —
    {"id":"l33","emoji":"🎲","nombre":"Golpe de Suerte","desc":"Gana con todos los indicadores exactamente = 50.",
     "como":"Cierra la partida con los 4 indicadores en exactamente 50.","tipo":"exacto","meta":50,"estrellas":12},
    {"id":"l34","emoji":"🌪️","nombre":"Sobreviviente","desc":"Supera 5 eventos negativos seguidos.",
     "como":"Recibe 5 eventos negativos consecutivos sin colapsar.","tipo":"eventos_neg_seguidos","meta":5,"estrellas":8},
    {"id":"l35","emoji":"🚀","nombre":"Ciudad del Futuro","desc":"Termina con Energía y Medio Ambiente > 85.",
     "como":"Cierra con Energía > 85 y Medio Ambiente > 85 en la misma partida.","tipo":"doble_indicador","inds":["energia","medio_ambiente"],"meta":85,"estrellas":9},
    {"id":"l36","emoji":"🧩","nombre":"Equilibrista","desc":"Los 4 indicadores dentro del rango 45–65 al final.",
     "como":"Termina con todos los indicadores entre 45 y 65.","tipo":"rango","min":45,"max":65,"estrellas":6},
    {"id":"l37","emoji":"🏃","nombre":"Sprint","desc":"Completa una partida en menos de 8 minutos.",
     "como":"Responde todas las preguntas rápido; el tiempo total de partida debe ser < 8 min.","tipo":"tiempo_partida","meta":480,"estrellas":5},
    {"id":"l38","emoji":"😤","nombre":"Nunca Me Rindo","desc":"Recupera la ciudad desde colapso inminente (prom < 35).",
     "como":"Con el promedio de indicadores por debajo de 35, logra terminar sin colapsar.","tipo":"recuperacion_total","meta":35,"estrellas":10},
    {"id":"l39","emoji":"🤝","nombre":"Equipo Unido","desc":"Cada estudiante responde al menos 1 pregunta correcta.",
     "como":"Todos los miembros del grupo aciertan 1 vez en la misma partida.","tipo":"todos_aciertan","meta":1,"estrellas":5},
    {"id":"l40","emoji":"🎯","nombre":"Francotirador","desc":"3 preguntas correctas de Difícil en 1 partida.",
     "como":"Acierta 3 preguntas de nivel Difícil dentro de la misma partida.","tipo":"correctas_dif_partida","meta":3,"estrellas":6},
    # — Ranking —
    {"id":"l41","emoji":"🥇","nombre":"Top 1","desc":"Alcanza el puesto #1 del ranking en cualquier dificultad.",
     "como":"Tu grupo debe tener el mayor puntaje en el ranking de alguna dificultad.","tipo":"ranking_top","meta":1,"estrellas":8},
    {"id":"l42","emoji":"🥈","nombre":"Top 3","desc":"Alcanza el podio (top 3) del ranking.",
     "como":"Tu grupo debe quedar entre los 3 primeros en el ranking.","tipo":"ranking_top","meta":3,"estrellas":5},
    # — Partidas acumuladas —
    {"id":"l43","emoji":"📅","nombre":"Constante","desc":"Juega 5 partidas en total.",
     "como":"Completa 5 partidas en cualquier dificultad.","tipo":"partidas","meta":5,"estrellas":3},
    {"id":"l44","emoji":"📆","nombre":"Habitual","desc":"Juega 10 partidas en total.",
     "como":"Completa 10 partidas en cualquier dificultad.","tipo":"partidas","meta":10,"estrellas":5},
    {"id":"l45","emoji":"🌐","nombre":"Ciudadano del Mundo","desc":"Juega 20 partidas en total.",
     "como":"Completa 20 partidas.","tipo":"partidas","meta":20,"estrellas":8},
    # — Sin penalización —
    {"id":"l46","emoji":"🎯","nombre":"Sin Error","desc":"Completa una partida Fácil sin ningún fallo.",
     "como":"Las 10 preguntas deben responderse correctamente en Fácil.","tipo":"correctas_partida_dif","dif":"Fácil","meta":10,"estrellas":5},
    {"id":"l47","emoji":"💫","nombre":"Maestro sin Error","desc":"Completa una partida Normal sin ningún fallo.",
     "como":"Las 10 preguntas correctas en Normal.","tipo":"correctas_partida_dif","dif":"Normal","meta":10,"estrellas":8},
    {"id":"l48","emoji":"🔱","nombre":"Dios de la Ciudad","desc":"Completa una partida Difícil sin ningún fallo.",
     "como":"Las 10 preguntas correctas en Difícil.","tipo":"correctas_partida_dif","dif":"Difícil","meta":10,"estrellas":15},
    # — Sociales —
    {"id":"l49","emoji":"🗣️","nombre":"Equipo Grande","desc":"Registra un grupo de 5 estudiantes.",
     "como":"El grupo debe tener exactamente 5 miembros registrados.","tipo":"tam_grupo","meta":5,"estrellas":2},
    {"id":"l50","emoji":"🎮","nombre":"Adicto","desc":"Inicia una partida 3 días distintos.",
     "como":"Accede y empieza una partida en 3 fechas de calendario distintas.","tipo":"dias_jugados","meta":3,"estrellas":4},
]

# ── Logros destacados para el Lobby (máx 8) ──────────────────────────────────
LOGROS_LOBBY = ["l04","l06","l12","l13","l20","l25","l28","l04"]
LOGROS_LOBBY = ["l04","l06","l11","l12","l13","l20","l25","l28"]

# ── Preguntas: campo "dif" = "facil" | "normal" | "dificil" ──────────────────
PREGUNTAS = [
  # ── Python — Fácil ──
  {"cat":"Python","dif":"facil","q":"¿Cómo se imprime en Python?",
   "ops":["console.log()","print()","echo()","printf()"],"ok":1},
  {"cat":"Python","dif":"facil","q":"¿Qué tipo devuelve type(3.14)?",
   "ops":["<class 'int'>","<class 'float'>","<class 'str'>","<class 'double'>"],"ok":1},
  {"cat":"Python","dif":"facil","q":"¿Qué hace len()?",
   "ops":["Convierte a entero","Retorna la longitud","Imprime en pantalla","Crea una lista"],"ok":1},
  {"cat":"Python","dif":"facil","q":"¿Cómo se define una función?",
   "ops":["function f():","def f():","func f():","define f():"],"ok":1},
  {"cat":"Python","dif":"facil","q":"Resultado de 2 ** 3",
   "ops":["6","8","9","5"],"ok":1},
  {"cat":"Python","dif":"facil","q":"¿Tipo de dato de True?",
   "ops":["int","str","bool","float"],"ok":2},
  {"cat":"Python","dif":"facil","q":"¿Cómo se hace división entera?",
   "ops":["//","%%","\\","div"],"ok":0},
  {"cat":"Python","dif":"facil","q":"¿Qué hace input()?",
   "ops":["Imprime","Lee del usuario","Importa","Crea variables"],"ok":1},
  {"cat":"Python","dif":"facil","q":"¿Cómo agregar al final de una lista?",
   "ops":["lst.add(x)","lst.append(x)","lst.insert(x)","lst.push(x)"],"ok":1},
  {"cat":"Python","dif":"facil","q":"¿Estructura para recorrer una lista?",
   "ops":["foreach","for x in lista:","loop","while each"],"ok":1},
  {"cat":"Python","dif":"facil","q":"¿Resultado de 10 % 3?",
   "ops":["3","1","0","2"],"ok":1},
  {"cat":"Python","dif":"facil","q":"¿Cómo crear una lista vacía?",
   "ops":["list{}","[]","{}","()"],"ok":1},
  {"cat":"Python","dif":"facil","q":"¿Qué hace range(5)?",
   "ops":["[1,2,3,4,5]","[0,1,2,3,4]","[0,1,2,3,4,5]","[1,2,3,4]"],"ok":1},
  {"cat":"Python","dif":"facil","q":"¿Cómo se comenta una línea?",
   "ops":["// comentario","-- comentario","# comentario","/* comentario */"],"ok":2},
  {"cat":"Python","dif":"facil","q":"¿Qué operador compara igualdad?",
   "ops":["=","==","!=","==="],"ok":1},
  # ── Python — Normal ──
  {"cat":"Python","dif":"normal","q":"Salida de print('Hi'*2)",
   "ops":["HiHi","Hi2","Error","Hi Hi"],"ok":0},
  {"cat":"Python","dif":"normal","q":"¿Qué devuelve range(3)?",
   "ops":["[1,2,3]","[0,1,2,3]","range(0,3)","[0,1,2]"],"ok":2},
  {"cat":"Python","dif":"normal","q":"¿Qué hace sorted()?",
   "ops":["Modifica la lista","Retorna lista ordenada","Elimina duplicados","Invierte la lista"],"ok":1},
  {"cat":"Python","dif":"normal","q":"¿Diferencia entre list y tuple?",
   "ops":["Ninguna","list es mutable, tuple no","tuple es mutable, list no","Distinto orden"],"ok":1},
  {"cat":"Python","dif":"normal","q":"¿Cómo eliminar una clave de un dict?",
   "ops":["del d[clave]","d.remove(clave)","d.delete(clave)","d.pop_key(clave)"],"ok":0},
  {"cat":"Python","dif":"normal","q":"¿Qué retorna 'hola'.upper()?",
   "ops":["hola","HOLA","Hola","HoLa"],"ok":1},
  {"cat":"Python","dif":"normal","q":"¿Cómo se maneja una excepción?",
   "ops":["try/catch","try/except","error/handle","catch/throw"],"ok":1},
  {"cat":"Python","dif":"normal","q":"¿Qué hace zip(a, b)?",
   "ops":["Concatena","Une en pares","Comprime archivo","Ordena"],"ok":1},
  {"cat":"Python","dif":"normal","q":"¿Qué es una comprensión de lista?",
   "ops":["[x for x in lista]","(x for x in lista)","list(x in lista)","x -> lista"],"ok":0},
  {"cat":"Python","dif":"normal","q":"¿Qué hace enumerate()?",
   "ops":["Cuenta elementos","Itera con índice","Ordena","Filtra"],"ok":1},
  # ── Python — Difícil ──
  {"cat":"Python","dif":"dificil","q":"¿Qué es un decorador en Python?",
   "ops":["Una clase","Una función que modifica otra","Un tipo de loop","Un módulo"],"ok":1},
  {"cat":"Python","dif":"dificil","q":"¿Qué hace *args en una función?",
   "ops":["Argumentos con nombre","Lista de argumentos posicionales","Diccionario","Error"],"ok":1},
  {"cat":"Python","dif":"dificil","q":"¿Qué es un generador?",
   "ops":["Lista infinita","Función que usa yield","Módulo de números","Clase especial"],"ok":1},
  {"cat":"Python","dif":"dificil","q":"¿Complejidad de buscar en un dict?",
   "ops":["O(n)","O(log n)","O(1)","O(n²)"],"ok":2},
  {"cat":"Python","dif":"dificil","q":"¿Qué hace __str__ en una clase?",
   "ops":["Constructor","Representación en cadena","Destructor","Comparación"],"ok":1},
  {"cat":"Python","dif":"dificil","q":"¿Diferencia entre deepcopy y copy?",
   "ops":["Ninguna","deepcopy copia objetos anidados","copy es más rápido","deepcopy solo copia listas"],"ok":1},
  {"cat":"Python","dif":"dificil","q":"¿Qué es el GIL en Python?",
   "ops":["Global Import Layer","Global Interpreter Lock","General Index List","None de los anteriores"],"ok":1},
  # ── PSeInt — Fácil ──
  {"cat":"PSeInt","dif":"facil","q":"¿Cómo declarar variable en PSeInt?",
   "ops":["var x = 5","Definir x Como Entero","int x = 5","x = 5"],"ok":1},
  {"cat":"PSeInt","dif":"facil","q":"¿Instrucción para mostrar en PSeInt?",
   "ops":["print","Mostrar","Escribir","Display"],"ok":2},
  {"cat":"PSeInt","dif":"facil","q":"¿Cómo inicia un algoritmo en PSeInt?",
   "ops":["Start","Algoritmo Nombre","Begin","def main"],"ok":1},
  {"cat":"PSeInt","dif":"facil","q":"¿Instrucción para leer en PSeInt?",
   "ops":["Leer","Input","Capturar","Ingresar"],"ok":0},
  {"cat":"PSeInt","dif":"facil","q":"¿Cómo se escribe SI en PSeInt?",
   "ops":["if(c)then","Si(c)Entonces","when(c)","check(c)"],"ok":1},
  {"cat":"PSeInt","dif":"facil","q":"¿Operador de asignación en PSeInt?",
   "ops":["=","<-","->",":="],"ok":1},
  {"cat":"PSeInt","dif":"facil","q":"¿Palabra que cierra un SI-ENTONCES?",
   "ops":["End","FinSi","EndIf","Cerrar"],"ok":1},
  # ── PSeInt — Normal ──
  {"cat":"PSeInt","dif":"normal","q":"¿Cómo inicia ciclo MIENTRAS en PSeInt?",
   "ops":["while(c)do","Mientras(c)Hacer","loop(c)","repetir(c)"],"ok":1},
  {"cat":"PSeInt","dif":"normal","q":"¿Variable tipo real en PSeInt?",
   "ops":["Definir x Como Real","float x","real x","var x:real"],"ok":0},
  {"cat":"PSeInt","dif":"normal","q":"¿Ciclo FOR en PSeInt?",
   "ops":["for i=1 to 10","Para i<-1 Hasta 10 Hacer","loop i","repeat i"],"ok":1},
  {"cat":"PSeInt","dif":"normal","q":"¿Cómo termina un ciclo Para?",
   "ops":["End","FinPara","EndFor","StopFor"],"ok":1},
  {"cat":"PSeInt","dif":"normal","q":"¿Cómo concatenar strings en PSeInt?",
   "ops":["+","&","concat()","||"],"ok":0},
  # ── PSeInt — Difícil ──
  {"cat":"PSeInt","dif":"dificil","q":"¿Cómo se define un subproceso en PSeInt?",
   "ops":["function f()","SubProceso f()","def f():","proc f()"],"ok":1},
  {"cat":"PSeInt","dif":"dificil","q":"¿Cómo pasar parámetro por referencia en PSeInt?",
   "ops":["ref x","ByRef x","Por Referencia x","&x"],"ok":2},
  {"cat":"PSeInt","dif":"dificil","q":"¿Cómo se declara un arreglo en PSeInt?",
   "ops":["array a[10]","Dimension a[10]","var a[10]","list a(10)"],"ok":1},
  # ── Cálculo — Fácil ──
  {"cat":"Cálculo","dif":"facil","q":"Integral de 0 dx",
   "ops":["0","C","x+C","1"],"ok":1},
  {"cat":"Cálculo","dif":"facil","q":"Integral de 1 dx",
   "ops":["0","x+C","1/x+C","C"],"ok":1},
  {"cat":"Cálculo","dif":"facil","q":"∫ x dx = ?",
   "ops":["x+C","x²+C","x²/2+C","2x+C"],"ok":2},
  {"cat":"Cálculo","dif":"facil","q":"∫ eˣ dx = ?",
   "ops":["eˣ+C","x·eˣ+C","eˣ⁺¹+C","ln(x)+C"],"ok":0},
  {"cat":"Cálculo","dif":"facil","q":"∫ cos(x) dx = ?",
   "ops":["-sin(x)+C","sin(x)+C","-cos(x)+C","tan(x)+C"],"ok":1},
  {"cat":"Cálculo","dif":"facil","q":"∫ sin(x) dx = ?",
   "ops":["cos(x)+C","-cos(x)+C","sin(x)+C","tan(x)+C"],"ok":1},
  # ── Cálculo — Normal ──
  {"cat":"Cálculo","dif":"normal","q":"∫ 1/x dx = ?",
   "ops":["x²+C","ln|x|+C","1/x²+C","-1/x²+C"],"ok":1},
  {"cat":"Cálculo","dif":"normal","q":"∫ 3x² dx = ?",
   "ops":["x³+C","6x+C","3x+C","x³/3+C"],"ok":0},
  {"cat":"Cálculo","dif":"normal","q":"La integral definida representa geométricamente:",
   "ops":["Pendiente","Área bajo la curva","Derivada","Volumen"],"ok":1},
  {"cat":"Cálculo","dif":"normal","q":"∫ xⁿ dx (n≠-1) = ?",
   "ops":["n·xⁿ⁻¹+C","xⁿ⁺¹/(n+1)+C","xⁿ/n+C","n·xⁿ+C"],"ok":1},
  {"cat":"Cálculo","dif":"normal","q":"¿Qué indica el Teorema Fundamental del Cálculo?",
   "ops":["Derivada de suma","Relación derivada-integral","Regla de la cadena","Límites laterales"],"ok":1},
  # ── Cálculo — Difícil ──
  {"cat":"Cálculo","dif":"dificil","q":"∫₀¹ x² dx = ?",
   "ops":["1/2","1/3","1/4","2/3"],"ok":1},
  {"cat":"Cálculo","dif":"dificil","q":"¿Cómo se integra por partes?",
   "ops":["∫u dv = uv - ∫v du","∫u dv = uv + ∫v du","∫f·g = f'·g'","Ninguna"],"ok":0},
  {"cat":"Cálculo","dif":"dificil","q":"∫ sec²(x) dx = ?",
   "ops":["sin(x)+C","cos(x)+C","tan(x)+C","-cot(x)+C"],"ok":2},
  # ── Derivadas — Fácil ──
  {"cat":"Derivadas","dif":"facil","q":"Derivada de x²",
   "ops":["x","2x","x²","2"],"ok":1},
  {"cat":"Derivadas","dif":"facil","q":"Derivada de eˣ",
   "ops":["x·eˣ⁻¹","eˣ","eˣ⁺¹","ln(x)"],"ok":1},
  {"cat":"Derivadas","dif":"facil","q":"Derivada de sin(x)",
   "ops":["-sin(x)","cos(x)","-cos(x)","tan(x)"],"ok":1},
  {"cat":"Derivadas","dif":"facil","q":"Derivada de una constante k",
   "ops":["k","1","0","k-1"],"ok":2},
  {"cat":"Derivadas","dif":"facil","q":"Derivada de ln(x)",
   "ops":["eˣ","1/x","x·ln(x)","log(x)"],"ok":1},
  # ── Derivadas — Normal ──
  {"cat":"Derivadas","dif":"normal","q":"Derivada de cos(x)",
   "ops":["sin(x)","-sin(x)","cos(x)","tan(x)"],"ok":1},
  {"cat":"Derivadas","dif":"normal","q":"Regla de la cadena d/dx f(g(x))",
   "ops":["f'(x)·g'(x)","f'(g(x))·g'(x)","f(x)·g(x)","f'(x)+g'(x)"],"ok":1},
  {"cat":"Derivadas","dif":"normal","q":"Derivada de x³ - 4x + 2",
   "ops":["3x-4","3x²-4","x²-4","3x²+2"],"ok":1},
  {"cat":"Derivadas","dif":"normal","q":"Derivada de tan(x)",
   "ops":["cos²(x)","sec²(x)","-csc²(x)","sin(x)"],"ok":1},
  {"cat":"Derivadas","dif":"normal","q":"Derivada de x·sin(x) (regla del producto)",
   "ops":["sin(x)","cos(x)","sin(x)+x·cos(x)","x·cos(x)"],"ok":2},
  # ── Derivadas — Difícil ──
  {"cat":"Derivadas","dif":"dificil","q":"Derivada de arctan(x)",
   "ops":["1/(1-x²)","1/(1+x²)","1/√(1-x²)","ln(x)"],"ok":1},
  {"cat":"Derivadas","dif":"dificil","q":"Derivada implícita: x²+y²=1 → dy/dx",
   "ops":["x/y","y/x","-x/y","-y/x"],"ok":2},
  {"cat":"Derivadas","dif":"dificil","q":"Derivada de xˣ",
   "ops":["x·xˣ⁻¹","xˣ(1+ln x)","ln(x)·xˣ","xˣ/ln(x)"],"ok":1},
  # ── Física MRU — Fácil ──
  {"cat":"Física MRU","dif":"facil","q":"En MRU la velocidad es:",
   "ops":["Acelerada","Constante","Nula","Variable"],"ok":1},
  {"cat":"Física MRU","dif":"facil","q":"Fórmula del MRU",
   "ops":["d=v·t","d=v²/2a","v=a·t","F=m·a"],"ok":0},
  {"cat":"Física MRU","dif":"facil","q":"En MRU la aceleración es:",
   "ops":["Máxima","Creciente","Cero","Variable"],"ok":2},
  {"cat":"Física MRU","dif":"facil","q":"Auto recorre 120 km en 2 h. ¿Velocidad?",
   "ops":["50 km/h","60 km/h","70 km/h","80 km/h"],"ok":1},
  # ── Física MRU — Normal ──
  {"cat":"Física MRU","dif":"normal","q":"Pendiente en gráfica posición-tiempo del MRU:",
   "ops":["Aceleración","Fuerza","Velocidad","Masa"],"ok":2},
  {"cat":"Física MRU","dif":"normal","q":"v=10 m/s, t=5 s → distancia:",
   "ops":["2 m","15 m","50 m","100 m"],"ok":2},
  {"cat":"Física MRU","dif":"normal","q":"Gráfica v-t en MRU:",
   "ops":["Curva ascendente","Horizontal","Vertical","Diagonal"],"ok":1},
  {"cat":"Física MRU","dif":"normal","q":"Unidad de velocidad en SI:",
   "ops":["km/h","m/s","cm/s","mph"],"ok":1},
  # ── Física MRU — Difícil ──
  {"cat":"Física MRU","dif":"dificil","q":"Un tren viaja 360 km en 3 h. ¿Cuánto en 45 min?",
   "ops":["60 km","75 km","90 km","120 km"],"ok":2},
  {"cat":"Física MRU","dif":"dificil","q":"Dos móviles se acercan a 40 y 60 m/s. ¿Velocidad relativa?",
   "ops":["20 m/s","40 m/s","60 m/s","100 m/s"],"ok":3},
  # ── Física MRUA — Fácil ──
  {"cat":"Física MRUA","dif":"facil","q":"¿Qué caracteriza al MRUA?",
   "ops":["Velocidad cte","Aceleración cte","Aceleración nula","Posición fija"],"ok":1},
  {"cat":"Física MRUA","dif":"facil","q":"v=v₀+a·t corresponde a:",
   "ops":["MRU","Caída libre","MRUA","MCU"],"ok":2},
  {"cat":"Física MRUA","dif":"facil","q":"Si a=0, MRUA se convierte en:",
   "ops":["Caída libre","MCU","MRU","Reposo"],"ok":2},
  # ── Física MRUA — Normal ──
  {"cat":"Física MRUA","dif":"normal","q":"Reposo, a=3 m/s². ¿Tiempo para 15 m/s?",
   "ops":["3 s","4 s","5 s","6 s"],"ok":2},
  {"cat":"Física MRUA","dif":"normal","q":"Área bajo v-t en MRUA representa:",
   "ops":["Aceleración","Fuerza","Desplazamiento","Potencia"],"ok":2},
  {"cat":"Física MRUA","dif":"normal","q":"d=v₀t+½at² es:",
   "ops":["Velocidad final","Desplazamiento MRUA","Fuerza neta","Energía"],"ok":1},
  {"cat":"Física MRUA","dif":"normal","q":"v²=v₀²+2ad es la ecuación de:",
   "ops":["Energía","Velocidad sin tiempo","Posición","Impulso"],"ok":1},
  # ── Física MRUA — Difícil ──
  {"cat":"Física MRUA","dif":"dificil","q":"Cuerpo cae desde 80 m. ¿Tiempo? (g=10)",
   "ops":["2 s","3 s","4 s","5 s"],"ok":2},
  {"cat":"Física MRUA","dif":"dificil","q":"v₀=20 m/s, a=-4 m/s². ¿Distancia hasta parar?",
   "ops":["25 m","40 m","50 m","80 m"],"ok":2},
  # ── Matrices — Fácil ──
  {"cat":"Matrices","dif":"facil","q":"¿Qué es una matriz cuadrada?",
   "ops":["Más filas que col","Filas=Columnas","Solo una fila","Elementos iguales"],"ok":1},
  {"cat":"Matrices","dif":"facil","q":"La transpuesta intercambia:",
   "ops":["Filas por columnas","Sumas por restas","Signos","Diagonales"],"ok":0},
  {"cat":"Matrices","dif":"facil","q":"¿Qué es la matriz identidad?",
   "ops":["Matriz de ceros","Unos en diagonal","Triangular","Nula"],"ok":1},
  {"cat":"Matrices","dif":"facil","q":"Traza de una matriz es:",
   "ops":["Determinante","Suma diagonal principal","Mayor elemento","Transpuesta"],"ok":1},
  # ── Matrices — Normal ──
  {"cat":"Matrices","dif":"normal","q":"A=[1,2;3,4], B=[3,4;2,1]. A+B=?",
   "ops":["[4,6;5,5]","[3,8;6,4]","[2,4;1,6]","[1,6;3,8]"],"ok":0},
  {"cat":"Matrices","dif":"normal","q":"Condición para multiplicar A×B:",
   "ops":["Ambas cuadradas","Col(A)=Fil(B)","Fil(A)=Fil(B)","A=B"],"ok":1},
  {"cat":"Matrices","dif":"normal","q":"Si det(A)≠0, A es:",
   "ops":["Invertible","Singular","Identidad","Ortogonal"],"ok":0},
  {"cat":"Matrices","dif":"normal","q":"Dimensión de producto 2×3 por 3×4:",
   "ops":["3×3","2×4","3×4","2×3"],"ok":1},
  {"cat":"Matrices","dif":"normal","q":"Matriz triangular superior tiene:",
   "ops":["Todo cero","Ceros debajo diagonal","Ceros encima diagonal","Solo diagonal"],"ok":1},
  # ── Matrices — Difícil ──
  {"cat":"Matrices","dif":"dificil","q":"det([1,2;3,4]) = ?",
   "ops":["10","-2","2","-10"],"ok":1},
  {"cat":"Matrices","dif":"dificil","q":"A=[1,2;3,4]. A⁻¹ = ?",
   "ops":["[-2,1;1.5,-0.5]","[4,-2;-3,1]","[0.5,1;1.5,2]","No existe"],"ok":0},
  {"cat":"Matrices","dif":"dificil","q":"Rango de [[1,2,3],[2,4,6]] =",
   "ops":["3","2","1","0"],"ok":2},
  # ── Lógica — Fácil ──
  {"cat":"Lógica","dif":"facil","q":"¿Qué es una tautología?",
   "ops":["Siempre falsa","Siempre verdadera","A veces verdadera","Depende de variables"],"ok":1},
  {"cat":"Lógica","dif":"facil","q":"¿Tabla de verdad de p AND q? (p=V, q=F)",
   "ops":["V","F","V o F","Indeterminado"],"ok":1},
  {"cat":"Lógica","dif":"facil","q":"¿p OR q cuando p=F, q=F?",
   "ops":["V","F","Indeterminado","Nulo"],"ok":1},
  {"cat":"Lógica","dif":"facil","q":"NOT(V) = ?",
   "ops":["V","F","1","Nulo"],"ok":1},
  # ── Lógica — Normal ──
  {"cat":"Lógica","dif":"normal","q":"¿Ley de De Morgan para NOT(A AND B)?",
   "ops":["NOT A AND NOT B","NOT A OR NOT B","A OR B","A AND B"],"ok":1},
  {"cat":"Lógica","dif":"normal","q":"p→q es falso solo cuando:",
   "ops":["p=V, q=V","p=F, q=V","p=V, q=F","p=F, q=F"],"ok":2},
  {"cat":"Lógica","dif":"normal","q":"¿Qué es una contradicción?",
   "ops":["Siempre verdadera","Siempre falsa","Variable","Ninguna"],"ok":1},
  # ── Lógica — Difícil ──
  {"cat":"Lógica","dif":"dificil","q":"Forma normal conjuntiva (FNC) es:",
   "ops":["Suma de productos","Producto de sumas","Solo disyunciones","Solo conjunciones"],"ok":1},
  {"cat":"Lógica","dif":"dificil","q":"¿Cuántas filas tiene una tabla de verdad con 3 variables?",
   "ops":["4","6","8","16"],"ok":2},
  # ── Álgebra — Fácil ──
  {"cat":"Álgebra","dif":"facil","q":"Simplificar x² · x³ =",
   "ops":["x⁵","x⁶","2x⁵","x"],"ok":0},
  {"cat":"Álgebra","dif":"facil","q":"¿Cuánto es (x+2)(x-2)?",
   "ops":["x²+4","x²-4","x²+4x+4","x²-4x+4"],"ok":1},
  {"cat":"Álgebra","dif":"facil","q":"Resolver: 2x+4=10 → x=",
   "ops":["2","3","4","5"],"ok":1},
  {"cat":"Álgebra","dif":"facil","q":"¿Qué es una ecuación cuadrática?",
   "ops":["Grado 1","Grado 2","Grado 3","Grado 4"],"ok":1},
  # ── Álgebra — Normal ──
  {"cat":"Álgebra","dif":"normal","q":"Raíces de x²-5x+6=0",
   "ops":["2 y 3","1 y 6","2 y -3","-2 y -3"],"ok":0},
  {"cat":"Álgebra","dif":"normal","q":"Fórmula cuadrática: x=",
   "ops":["(-b±√Δ)/2a","(-b±√Δ)/a","(b±√Δ)/2a","(-b)/2a"],"ok":0},
  {"cat":"Álgebra","dif":"normal","q":"Discriminante Δ=b²-4ac>0 implica:",
   "ops":["Sin raíces reales","Una raíz doble","Dos raíces reales distintas","Raíces complejas"],"ok":2},
  # ── Álgebra — Difícil ──
  {"cat":"Álgebra","dif":"dificil","q":"Simplificar (x²-4)/(x-2):",
   "ops":["x+2","x-2","x²+2","(x+2)(x-2)"],"ok":0},
  {"cat":"Álgebra","dif":"dificil","q":"Resolver sistema: x+y=5, x-y=1 → x=",
   "ops":["1","2","3","4"],"ok":2},
  # ── Estadística — Fácil ──
  {"cat":"Estadística","dif":"facil","q":"¿Qué es la media aritmética?",
   "ops":["Valor más frecuente","Suma dividida entre n","Valor central","Rango"],"ok":1},
  {"cat":"Estadística","dif":"facil","q":"Media de [2,4,6,8,10] =",
   "ops":["5","6","7","8"],"ok":1},
  {"cat":"Estadística","dif":"facil","q":"¿Qué es la mediana?",
   "ops":["Media","Valor central ordenado","Valor más frecuente","Rango"],"ok":1},
  {"cat":"Estadística","dif":"facil","q":"¿Qué es la moda?",
   "ops":["Promedio","Valor más frecuente","Valor central","Desviación"],"ok":1},
  # ── Estadística — Normal ──
  {"cat":"Estadística","dif":"normal","q":"Varianza de [2,4,6]: media=4 → σ²=",
   "ops":["2","4/3","4","8/3"],"ok":3},
  {"cat":"Estadística","dif":"normal","q":"¿Qué mide la desviación estándar?",
   "ops":["Valor central","Dispersión","Frecuencia","Probabilidad"],"ok":1},
  {"cat":"Estadística","dif":"normal","q":"Probabilidad de sacar par en dado: P=",
   "ops":["1/3","1/2","2/3","1/6"],"ok":1},
  {"cat":"Estadística","dif":"normal","q":"Rango = ?",
   "ops":["Media - Mediana","Máximo - Mínimo","Suma/n","Desviación/n"],"ok":1},
  # ── Estadística — Difícil ──
  {"cat":"Estadística","dif":"dificil","q":"P(A∩B) si A y B son independientes:",
   "ops":["P(A)+P(B)","P(A)·P(B)","P(A|B)","P(A)-P(B)"],"ok":1},
  {"cat":"Estadística","dif":"dificil","q":"Distribución normal: 68% de datos cae en:",
   "ops":["μ±σ","μ±2σ","μ±3σ","μ±0.5σ"],"ok":0},
  {"cat":"Estadística","dif":"dificil","q":"Coeficiente de correlación r∈:",
   "ops":["[0,1]","[-1,1]","(-∞,∞)","[0,∞)"],"ok":1},
]
